- name: Actualizar Dependencias
  apt:
    name: '*'
    state: latest

- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Habilitar y arrancar Apache
  service:
    name: apache2
    state: started
    enabled: yes
