- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Establecer permisos
  file:
    path: /var/www/html/wordpress
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Copiar archivo de configuración
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
