apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  selector:
    app: nest-dev # "nest-prod" si estás corriendo producción
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
